[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "LicenseRef-ring",
    "MPL-2.0",
    "MIT",
    "Unicode-DFS-2016",
]

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]
