name: pull_request_checks

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Format check
        run: cargo fmt --check
        shell: nix develop -i --command bash -e {0}
      - name: License check
        run: cargo deny check licenses sources
        shell: nix develop -i --command bash -e {0}
      - name: Static analysis
        run: |
          cargo clippy --all-targets --all-features -- \
          -D warnings -W clippy::all -W clippy::pedantic -W clippy::cargo \
          -A clippy::multiple_crate_versions
        shell: nix develop -i --command bash -e {0}
      - name: Unit Tests and Coverage
        run: cargo llvm-cov --ignore-filename-regex /build/*
        shell: nix develop -i --command bash -e {0}
      - name: Build
        run: cargo build
        shell: nix develop -i --command bash -e {0}

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build application
        run: nix build
